# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-03 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20181030_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='address',
            field=models.CharField(max_length=150, verbose_name='机构地址'),
        ),
    ]
