# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-03 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20181103_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='work_years',
            field=models.IntegerField(default=0, verbose_name='工作年限'),
        ),
    ]
